name: Apply labels to new issues and add them to the janus-planning project

on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Apply Label to Issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["status/triage"]
            })
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Zaperex/projects/2
          github-token: ${{ secrets.PRIVATE_TOKEN }}
          labeled: status/triage