name: Apply labels to issues

on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Apply Label to Issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["status/triage"]
            })
      - name: Trigger Add Issue to Project Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          event-type: label_applied